// AUTO-GENERATED by kaggriculture.sim.generate_constants from vendor/kaggriculture.py
// (via kaggriculture.model.constants). Do not hand-edit -- regenerate instead:
//     uv run python -m kaggriculture.sim.generate_constants
#pragma once

#include <array>

namespace kaggriculture::sim {

struct CropDef {
    int seed;
    int first_yield_day;
    int max_yield_day;
    int interval;
    int max_yield;
    bool ongoing;
};

struct AnimalDef {
    int cost;
    int structure;    // 0 = COOP, 1 = PASTURE
    int first_yield_day;
    int interval;
    int max_held;
    int product_item; // Item enum index of the harvested product (e.g. GOOSE -> EGG)
};

// Order: WHEAT, CARROT, TOMATO, STRAWBERRY, MELON (enum Crop).
constexpr std::array<CropDef, 5> CROPS = {{
    {10, 2, 4, 0, 6, false},  // WHEAT
    {20, 2, 3, 0, 4, false},  // CARROT
    {50, 8, 8, 1, 4, true},  // TOMATO
    {100, 10, 10, 2, 4, true},  // STRAWBERRY
    {80, 10, 12, 0, 6, false},  // MELON
}};

// Order: GOOSE, COW, SHEEP (enum Animal).
constexpr std::array<AnimalDef, 3> ANIMALS = {{
    {300, 0, 4, 1, 4, 5},  // GOOSE -> EGG
    {400, 1, 8, 2, 6, 6},  // COW -> MILK
    {500, 1, 6, 3, 6, 7},  // SHEEP -> WOOL
}};

}  // namespace kaggriculture::sim
