// AUTO-GENERATED by kaggriculture.sim.generate_constants from vendor/kaggriculture.py
// (via kaggriculture.model.constants). Do not hand-edit -- regenerate instead:
//     uv run python -m kaggriculture.sim.generate_constants
#pragma once

#include <array>
#include <cstdint>

namespace kaggriculture::sim {

struct CropDef {
    int seed;
    int first_yield_day;
    int max_yield_day;
    int interval;
    int max_yield;
    bool ongoing;
};

struct AnimalDef {
    int cost;
    int structure;    // 0 = COOP, 1 = PASTURE
    int first_yield_day;
    int interval;
    int max_held;
    int product_item; // Item enum index of the harvested product (e.g. GOOSE -> EGG)
};

// Order: WHEAT, CARROT, TOMATO, STRAWBERRY, MELON (enum Crop).
constexpr std::array<CropDef, 5> CROPS = {{
    {10, 2, 4, 0, 6, false},  // WHEAT
    {20, 2, 3, 0, 4, false},  // CARROT
    {50, 8, 8, 1, 4, true},  // TOMATO
    {100, 10, 10, 2, 4, true},  // STRAWBERRY
    {80, 10, 12, 0, 6, false},  // MELON
}};

// Order: GOOSE, COW, SHEEP (enum Animal).
constexpr std::array<AnimalDef, 3> ANIMALS = {{
    {300, 0, 4, 1, 4, 5},  // GOOSE -> EGG
    {400, 1, 8, 2, 6, 6},  // COW -> MILK
    {500, 1, 6, 3, 6, 7},  // SHEEP -> WOOL
}};

enum class ShapeFunc : uint8_t { LINEAR, SQ, SQRT, LOG, LOG10, HINGE };

struct MarketParamDef {
    int base;
    int I0;
    int T;
    ShapeFunc below_func;
    double below_target;
    ShapeFunc above_func;
    double above_target;
};

// Order: the 9 PRODUCTS, i.e. Item indices [0, N_PRODUCTS) -- WHEAT..FERTILIZER.
constexpr std::array<MarketParamDef, 9> MARKET_PARAMS = {{
    {25, 10000, 400, static_cast<ShapeFunc>(2), 0.8, static_cast<ShapeFunc>(3), 0.2},  // WHEAT
    {35, 10000, 450, static_cast<ShapeFunc>(5), 1.0, static_cast<ShapeFunc>(2), 0.7},  // CARROT
    {60, 10000, 200, static_cast<ShapeFunc>(5), 0.4, static_cast<ShapeFunc>(2), 0.6},  // TOMATO
    {120, 10000, 100, static_cast<ShapeFunc>(2), 0.7, static_cast<ShapeFunc>(0), 1.6},  // STRAWBERRY
    {250, 10000, 300, static_cast<ShapeFunc>(3), 0.2, static_cast<ShapeFunc>(1), 3.6},  // MELON
    {50, 10000, 332, static_cast<ShapeFunc>(5), 0.4, static_cast<ShapeFunc>(3), 0.2},  // EGG
    {160, 10000, 122, static_cast<ShapeFunc>(2), 0.6, static_cast<ShapeFunc>(0), 1.6},  // MILK
    {200, 10000, 105, static_cast<ShapeFunc>(3), 0.2, static_cast<ShapeFunc>(1), 3.2},  // WOOL
    {100, 10000, 200, static_cast<ShapeFunc>(0), 0.4, static_cast<ShapeFunc>(0), 0.4},  // FERTILIZER
}};

struct ShopDef {
    int n_products;
    int products[4];  // Item indices; only the first n_products entries are valid
};

// ShopType enum order: vendor's `sorted(SHOPS)` -- the exact pool `rng.choice` draws from.
enum class ShopType : uint8_t { BAKERY, BRUNCH_SPOT, FARMERS_MARKET, ICE_CREAM_SHOP, PET_CAFE, PIZZA_SHOP, SMOOTHIE_SHOP, YARN_STORE, COUNT };

constexpr std::array<ShopDef, 8> SHOPS = {{
    {2, {5, 0, 0, 0}},  // BAKERY: EGG, WHEAT
    {3, {5, 0, 3, 0}},  // BRUNCH_SPOT: EGG, WHEAT, STRAWBERRY
    {4, {0, 1, 2, 3}},  // FARMERS_MARKET: WHEAT, CARROT, TOMATO, STRAWBERRY
    {3, {3, 6, 0, 0}},  // ICE_CREAM_SHOP: STRAWBERRY, MILK, WHEAT
    {1, {1, 0, 0, 0}},  // PET_CAFE: CARROT
    {3, {6, 2, 0, 0}},  // PIZZA_SHOP: MILK, TOMATO, WHEAT
    {2, {3, 6, 0, 0}},  // SMOOTHIE_SHOP: STRAWBERRY, MILK
    {1, {7, 0, 0, 0}},  // YARN_STORE: WOOL
}};

// Cost of the n-th quadrant unlocked beyond NW (n=0 -> NE, 1 -> SW, 2 -> SE in
// quadrant_of()'s indexing -- vendor's LAND_ORDER is exactly quadrant indices 1,2,3).
constexpr std::array<int, 3> LAND_PRICES = {{1000, 2000, 4000}};

constexpr int MAX_SHOP_INSTANCES = 8;

// Configuration defaults (vendor/kaggriculture.json's schema `default` fields, via
// kaggriculture.model.constants.CONFIG_DEFAULTS -- the engine reads each of these inline
// via `get(cfg, "key", default)` rather than one dict; this is the single collected copy.
namespace config_defaults {
constexpr int BOARD_SIZE = 10;
constexpr double STARTING_MONEY = 3000.0;
constexpr int MAX_MARKET_ORDERS_PER_TURN = 10;
constexpr int TURNS_PER_DAY = 24;
constexpr int SHED_CAPACITY = 100;
constexpr double WEED_SPAWN_CHANCE = 0.005;
constexpr int TOWN_SHOP_UNLOCK_INTERVAL = 3;
constexpr int TOWN_SHOP_SELL_INTERVAL = 4;
constexpr int TOWN_CENTER_SELL_INTERVAL = 24;
constexpr int FARM_HAND_COST_MULT = 1;
constexpr int EPISODE_STEPS = 720;
}  // namespace config_defaults

}  // namespace kaggriculture::sim
