"""Generates sim/constants_generated.hpp from kaggriculture.model.constants (itself sourced from
vendor/kaggriculture.py — see issue 002/004). Never hand-type CROPS/ANIMALS values into the C++
port; regenerate this file instead:

    uv run python -m kaggriculture.sim.generate_constants

Table row order matches the `Crop`/`Animal` enums declared in sim.hpp (WHEAT, CARROT, TOMATO,
STRAWBERRY, MELON / GOOSE, COW, SHEEP) — the same order vendor/kaggriculture.py's CROPS/ANIMALS
dicts already use, so no reordering happens here, just a format change.
"""

from pathlib import Path

from kaggriculture.model.constants import ANIMALS, CROPS

OUT_PATH = Path(__file__).parent / "constants_generated.hpp"

_CROP_ORDER = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON"]
_ANIMAL_ORDER = ["GOOSE", "COW", "SHEEP"]
_STRUCTURE_INDEX = {"COOP": 0, "PASTURE": 1}
# Item enum order (sim.hpp): WHEAT, CARROT, TOMATO, STRAWBERRY, MELON, EGG, MILK, WOOL,
# FERTILIZER, GOOSE, COW, SHEEP.
_ITEM_INDEX = {
    "WHEAT": 0, "CARROT": 1, "TOMATO": 2, "STRAWBERRY": 3, "MELON": 4,
    "EGG": 5, "MILK": 6, "WOOL": 7, "FERTILIZER": 8, "GOOSE": 9, "COW": 10, "SHEEP": 11,
}


def generate() -> str:
    assert list(CROPS) == _CROP_ORDER, "CROPS order drifted from the Crop enum; update both"
    assert list(ANIMALS) == _ANIMAL_ORDER, "ANIMALS order drifted from the Animal enum; update both"

    lines = [
        "// AUTO-GENERATED by kaggriculture.sim.generate_constants from vendor/kaggriculture.py",
        "// (via kaggriculture.model.constants). Do not hand-edit -- regenerate instead:",
        "//     uv run python -m kaggriculture.sim.generate_constants",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace kaggriculture::sim {",
        "",
        "struct CropDef {",
        "    int seed;",
        "    int first_yield_day;",
        "    int max_yield_day;",
        "    int interval;",
        "    int max_yield;",
        "    bool ongoing;",
        "};",
        "",
        "struct AnimalDef {",
        "    int cost;",
        "    int structure;    // 0 = COOP, 1 = PASTURE",
        "    int first_yield_day;",
        "    int interval;",
        "    int max_held;",
        "    int product_item; // Item enum index of the harvested product (e.g. GOOSE -> EGG)",
        "};",
        "",
        "// Order: WHEAT, CARROT, TOMATO, STRAWBERRY, MELON (enum Crop).",
        "constexpr std::array<CropDef, 5> CROPS = {{",
    ]
    for name in _CROP_ORDER:
        c = CROPS[name]
        lines.append(
            f"    {{{c['seed']}, {c['first_yield_day']}, {c['max_yield_day']}, "
            f"{c['interval']}, {c['max_yield']}, {'true' if c['ongoing'] else 'false'}}},  // {name}"
        )
    lines += [
        "}};",
        "",
        "// Order: GOOSE, COW, SHEEP (enum Animal).",
        "constexpr std::array<AnimalDef, 3> ANIMALS = {{",
    ]
    for name in _ANIMAL_ORDER:
        a = ANIMALS[name]
        struct_idx = _STRUCTURE_INDEX[a["structure"]]
        product_idx = _ITEM_INDEX[a["product"]]
        lines.append(
            f"    {{{a['cost']}, {struct_idx}, {a['first_yield_day']}, {a['interval']}, "
            f"{a['max_held']}, {product_idx}}},  // {name} -> {a['product']}"
        )
    lines += [
        "}};",
        "",
        "}  // namespace kaggriculture::sim",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT_PATH.write_text(generate())
    print(f"wrote {OUT_PATH}")
