"""Generates sim/constants_generated.hpp from kaggriculture.model.constants (itself sourced from
vendor/kaggriculture.py — see issue 002/004). Never hand-type CROPS/ANIMALS values into the C++
port; regenerate this file instead:

    uv run python -m kaggriculture.sim.generate_constants

Table row order matches the `Crop`/`Animal` enums declared in sim.hpp (WHEAT, CARROT, TOMATO,
STRAWBERRY, MELON / GOOSE, COW, SHEEP) — the same order vendor/kaggriculture.py's CROPS/ANIMALS
dicts already use, so no reordering happens here, just a format change.
"""

from pathlib import Path

from kaggriculture.model.constants import ANIMALS, CONFIG_DEFAULTS, CROPS, LAND_PRICES, MARKET_PARAMS, MAX_SHOP_INSTANCES, SHOPS

OUT_PATH = Path(__file__).parent / "constants_generated.hpp"

_CROP_ORDER = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON"]
_ANIMAL_ORDER = ["GOOSE", "COW", "SHEEP"]
_STRUCTURE_INDEX = {"COOP": 0, "PASTURE": 1}
# Item enum order (sim.hpp): WHEAT, CARROT, TOMATO, STRAWBERRY, MELON, EGG, MILK, WOOL,
# FERTILIZER, GOOSE, COW, SHEEP.
_ITEM_INDEX = {
    "WHEAT": 0, "CARROT": 1, "TOMATO": 2, "STRAWBERRY": 3, "MELON": 4,
    "EGG": 5, "MILK": 6, "WOOL": 7, "FERTILIZER": 8, "GOOSE": 9, "COW": 10, "SHEEP": 11,
}
# Item enum order restricted to the 9 tradeable PRODUCTS (Item indices [0, N_PRODUCTS)).
_PRODUCT_ORDER = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG", "MILK", "WOOL", "FERTILIZER"]
_SHAPE_INDEX = {"linear": 0, "sq": 1, "sqrt": 2, "log": 3, "log10": 4, "hinge": 5}
# ShopType enum order: vendor's own `sorted(SHOPS)` -- the exact draw pool `rng.choice` samples
# from in `_end_of_day`. Must match, not just "some fixed order".
_SHOP_ORDER = sorted(SHOPS)
_MAX_SHOP_PRODUCTS = max(len(v) for v in SHOPS.values())


def generate() -> str:
    assert list(CROPS) == _CROP_ORDER, "CROPS order drifted from the Crop enum; update both"
    assert list(ANIMALS) == _ANIMAL_ORDER, "ANIMALS order drifted from the Animal enum; update both"

    lines = [
        "// AUTO-GENERATED by kaggriculture.sim.generate_constants from vendor/kaggriculture.py",
        "// (via kaggriculture.model.constants). Do not hand-edit -- regenerate instead:",
        "//     uv run python -m kaggriculture.sim.generate_constants",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace kaggriculture::sim {",
        "",
        "struct CropDef {",
        "    int seed;",
        "    int first_yield_day;",
        "    int max_yield_day;",
        "    int interval;",
        "    int max_yield;",
        "    bool ongoing;",
        "};",
        "",
        "struct AnimalDef {",
        "    int cost;",
        "    int structure;    // 0 = COOP, 1 = PASTURE",
        "    int first_yield_day;",
        "    int interval;",
        "    int max_held;",
        "    int product_item; // Item enum index of the harvested product (e.g. GOOSE -> EGG)",
        "};",
        "",
        "// Order: WHEAT, CARROT, TOMATO, STRAWBERRY, MELON (enum Crop).",
        "constexpr std::array<CropDef, 5> CROPS = {{",
    ]
    for name in _CROP_ORDER:
        c = CROPS[name]
        lines.append(
            f"    {{{c['seed']}, {c['first_yield_day']}, {c['max_yield_day']}, "
            f"{c['interval']}, {c['max_yield']}, {'true' if c['ongoing'] else 'false'}}},  // {name}"
        )
    lines += [
        "}};",
        "",
        "// Order: GOOSE, COW, SHEEP (enum Animal).",
        "constexpr std::array<AnimalDef, 3> ANIMALS = {{",
    ]
    for name in _ANIMAL_ORDER:
        a = ANIMALS[name]
        struct_idx = _STRUCTURE_INDEX[a["structure"]]
        product_idx = _ITEM_INDEX[a["product"]]
        lines.append(
            f"    {{{a['cost']}, {struct_idx}, {a['first_yield_day']}, {a['interval']}, "
            f"{a['max_held']}, {product_idx}}},  // {name} -> {a['product']}"
        )
    lines += [
        "}};",
        "",
        "enum class ShapeFunc : uint8_t { LINEAR, SQ, SQRT, LOG, LOG10, HINGE };",
        "",
        "struct MarketParamDef {",
        "    int base;",
        "    int I0;",
        "    int T;",
        "    ShapeFunc below_func;",
        "    double below_target;",
        "    ShapeFunc above_func;",
        "    double above_target;",
        "};",
        "",
        "// Order: the 9 PRODUCTS, i.e. Item indices [0, N_PRODUCTS) -- WHEAT..FERTILIZER.",
        "constexpr std::array<MarketParamDef, 9> MARKET_PARAMS = {{",
    ]
    for name in _PRODUCT_ORDER:
        p = MARKET_PARAMS[name]
        below = _SHAPE_INDEX[p["below_func"]]
        above = _SHAPE_INDEX[p["above_func"]]
        lines.append(
            f"    {{{p['base']}, {p['I0']}, {p['T']}, "
            f"static_cast<ShapeFunc>({below}), {p['below_target']}, "
            f"static_cast<ShapeFunc>({above}), {p['above_target']}}},  // {name}"
        )
    lines += [
        "}};",
        "",
        f"struct ShopDef {{",
        "    int n_products;",
        f"    int products[{_MAX_SHOP_PRODUCTS}];  // Item indices; only the first n_products entries are valid",
        "};",
        "",
        "// ShopType enum order: vendor's `sorted(SHOPS)` -- the exact pool `rng.choice` draws from.",
        "enum class ShopType : uint8_t { " + ", ".join(_SHOP_ORDER) + ", COUNT };",
        "",
        f"constexpr std::array<ShopDef, {len(_SHOP_ORDER)}> SHOPS = {{{{",
    ]
    for name in _SHOP_ORDER:
        products = SHOPS[name]
        idxs = [str(_ITEM_INDEX[p]) for p in products]
        padded = idxs + ["0"] * (_MAX_SHOP_PRODUCTS - len(idxs))
        lines.append(f"    {{{len(products)}, {{{', '.join(padded)}}}}},  // {name}: {', '.join(products)}")
    lines += [
        "}};",
        "",
        "// Cost of the n-th quadrant unlocked beyond NW (n=0 -> NE, 1 -> SW, 2 -> SE in",
        "// quadrant_of()'s indexing -- vendor's LAND_ORDER is exactly quadrant indices 1,2,3).",
        f"constexpr std::array<int, 3> LAND_PRICES = {{{{{', '.join(str(v) for v in LAND_PRICES)}}}}};",
        "",
        f"constexpr int MAX_SHOP_INSTANCES = {MAX_SHOP_INSTANCES};",
        "",
        "// Configuration defaults (vendor/kaggriculture.json's schema `default` fields, via",
        "// kaggriculture.model.constants.CONFIG_DEFAULTS -- the engine reads each of these inline",
        "// via `get(cfg, \"key\", default)` rather than one dict; this is the single collected copy.",
        "namespace config_defaults {",
        f"constexpr int BOARD_SIZE = {CONFIG_DEFAULTS['boardSize']};",
        f"constexpr double STARTING_MONEY = {CONFIG_DEFAULTS['startingMoney']}.0;",
        f"constexpr int MAX_MARKET_ORDERS_PER_TURN = {CONFIG_DEFAULTS['maxMarketOrdersPerTurn']};",
        f"constexpr int TURNS_PER_DAY = {CONFIG_DEFAULTS['turnsPerDay']};",
        f"constexpr int SHED_CAPACITY = {CONFIG_DEFAULTS['shedCapacity']};",
        f"constexpr double WEED_SPAWN_CHANCE = {CONFIG_DEFAULTS['weedSpawnChance']};",
        f"constexpr int TOWN_SHOP_UNLOCK_INTERVAL = {CONFIG_DEFAULTS['townShopUnlockInterval']};",
        f"constexpr int TOWN_SHOP_SELL_INTERVAL = {CONFIG_DEFAULTS['townShopSellInterval']};",
        f"constexpr int TOWN_CENTER_SELL_INTERVAL = {CONFIG_DEFAULTS['townCenterSellInterval']};",
        f"constexpr int FARM_HAND_COST_MULT = {CONFIG_DEFAULTS['farmHandCostMult']};",
        f"constexpr int EPISODE_STEPS = {CONFIG_DEFAULTS['episodeSteps']};",
        "}  // namespace config_defaults",
        "",
        "}  // namespace kaggriculture::sim",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT_PATH.write_text(generate())
    print(f"wrote {OUT_PATH}")
