"""Generates a frozen, self-contained snapshot of model/constants.py's *data* for packaging
into a submission.

constants.py locates its data by loading vendor/kaggriculture.py from an absolute repo path —
that path won't exist on Kaggle's grader (files land flat in /kaggle_simulations/agent/), so a
submission can't import constants.py as-is. Every value this module emits is machine-generated
from vendor/ (via constants.py, which is tested against vendor/ directly — see
tests/model/test_price.py etc.) at build time, never hand-typed; regenerate by rebuilding the
submission whenever vendor/ changes. See kaggriculture.submit.build.build_bundle.
"""

from kaggriculture.model import constants

_DATA_NAMES = [
    "CROPS",
    "ANIMALS",
    "PRODUCTS",
    "MARKET_PARAMS",
    "MARKET_I0",
    "PRICE_FLOOR",
    "HINGE_GAIN",
    "SHOPS",
    "TOWN_CENTER_PRODUCTS",
    "MAX_SHOP_INSTANCES",
    "LAND_ORDER",
    "LAND_PRICES",
    "FARM_HAND_COST_MULT",
    "FARMER_MOVES",
    "CONFIG_DEFAULTS",
]


def frozen_constants_source() -> str:
    lines = [
        '"""Frozen data snapshot of kaggriculture.model.constants, generated by',
        "kaggriculture.model.freeze.frozen_constants_source() for packaging (see its",
        'docstring). Never hand-edited; regenerate by rebuilding the submission."""',
        "",
    ]
    for name in _DATA_NAMES:
        lines.append(f"{name} = {getattr(constants, name)!r}")
    return "\n".join(lines) + "\n"
